name: "Discord PR Notification"
on:
  pull_request_target:
    types: [opened, closed, labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'Stale' }}
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT

      - name: Process PR body
        id: process_body
        run: |
          CLEAN_BODY=$(echo '${{ github.event.pull_request.body }}' | sed 's/<!--.*-->//g')
          CLEAN_BODY=$(echo "$CLEAN_BODY" | sed '/^[[:space:]]*$/d')
          CLEAN_BODY=$(echo "$CLEAN_BODY" | sed -E 's/<img[^>]*src="([^"]*)"[^>]*>/\1/g')
          CLEAN_BODY=$(echo "$CLEAN_BODY" | sed -E 's/<a[^>]*href="([^"]*)"[^>]*>([^<]*)<\/a>/[\2](\1)/g')
          CLEAN_BODY=$(echo "$CLEAN_BODY" | sed 's/<[^>]*>//g')
          CLEAN_BODY=$(echo "$CLEAN_BODY" | sed '/^[[:space:]]*$/d')
          CLEAN_BODY=$'\n'"$CLEAN_BODY"
          echo "CLEAN_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$CLEAN_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        uses: tgstation/discord-notify@v3
        if: >
          steps.secrets_set.outputs.SECRETS_ENABLED
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ github.event.pull_request.user.login }} - ${{ github.event.pull_request.title }}
          message: ${{ format('{0}{1}',
              (github.event.action == 'closed' &&
                (github.event.pull_request.merged == true && format('**Изменения из пулл реквеста {0} добавлены в билд.**', github.event.pull_request.number) ||
                format('**Пулл реквест {0} закрыт.**', github.event.pull_request.number)
              ) ||
              github.event.action == 'opened' &&
                format('**Пулл реквест {0} открыт.**', github.event.pull_request.number)
              ),
            (steps.process_body.outputs.CLEAN_BODY) || ''
            )}}
          include_image: false
          show_author: true
          avatar_url: https://cdn.discordapp.com/attachments/1284433984666734603/1403044127112958063/1984__.png?ex=68961e2b&is=6894ccab&hm=d7b5275db43299c38cfb4cb9dead55f1d8ec0191a556b8090fd81b11267c9dd0&
          username: GitHub
          title_url: "${{ github.event.pull_request.html_url }}"
