name: Check for DMI5

on:
  pull_request_target:
  workflow_run:
    workflows: ["Build and verify Rust library"]
    types: [completed]

jobs:
  check-dmi5:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ParadiseSS13/DMI5Checker@v1
      with:
        icons-path: 'icons'
