name: TGUI Auto-Rebuild on Public Conflicts

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-and-rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch target branch (e.g., master220)
        run: |
          git fetch origin ${{ github.base_ref }}  # Целевая ветка (base)

      - name: Check merge conflicts in tgui/public
        id: check-conflicts
        run: |
          # Пытаемся сделать мердж "вникуда" (чтобы проверить конфликты)
          git merge --no-commit --no-ff origin/${{ github.base_ref }} || true
          
          CONFLICT_FILES=$(git diff --name-only --diff-filter=U)
          echo "Conflicted files: $CONFLICT_FILES"

          BAD_CONFLICTS=0
          for FILE in $CONFLICT_FILES; do
            if [[ "$FILE" != "tgui/public/"* || "$FILE" == "tgui/public/tgui.html" ]]; then
              echo "Invalid conflict: $FILE"
              BAD_CONFLICTS=1
              break
            fi
          done

          # Если конфликты только в tgui/public (кроме tgui.html) — продолжаем
          if [ "$BAD_CONFLICTS" -eq 0 ] && [ -n "$CONFLICT_FILES" ]; then
            echo "safe_to_rebuild=true" >> $GITHUB_OUTPUT
          else
            echo "safe_to_rebuild=false" >> $GITHUB_OUTPUT
          fi

          git merge --abort

      - name: Rebuild TGUI (if safe)
        if: steps.check-conflicts.outputs.safe_to_rebuild == 'true'
        run: |
          cd tgui/public
          find . -type f -not -name 'tgui.html' -delete
          find . -type d -not -name '.' -exec rm -rf {} +
          cd ../..

          ./tgui/bin/tgui

          git config --local user.email "actions@github.com"
          git config --local user.name "TGUI Auto-Rebuild"
          git add tgui/public
          git commit -m "Auto-rebuild TGUI after conflicts"
          git push

      - name: Comment on PR (if rebuilt)
        if: steps.check-conflicts.outputs.safe_to_rebuild == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔧 Автоматически пересобрал TGUI после конфликтов в `tgui/public`. ' +
                    'Проверьте изменения и обновите PR, если нужно!'
            })

      - name: Comment on PR (if unsafe conflicts)
        if: steps.check-conflicts.outputs.safe_to_rebuild == 'false' && steps.check-conflicts.outputs.conflict_files != ''
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Обнаружены конфликты за пределами `tgui/public` или в `tgui.html`. ' +
                    'Нельзя автоматически пересобрать TGUI. Разрешите конфликты вручную.'
            })
